

title: un nuovo inizio
remote_theme: zendesk/jekyll-theme-zendesk-garden@main


search_enabled: true
auto_page_title: true

sidebar:
  - p2
  - label: pag3
    children:
      - p2
      - p2
  - p2
